{"metadata":{"role":"symbol","symbolKind":"case","roleHeading":"Case","externalID":"s:9VigramSDK19AuthenticationErrorO7failureyACSScACmF","title":"AuthenticationError.failure(_:)","modules":[{"name":"VigramSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failure"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/vigramsdk\/authenticationerror\/failure(_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/failure(_:)"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Authentication is failure - Other error received from server"}],"hierarchy":{"paths":[["doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failure"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.vigram.VigramSDK/documentation/VigramSDK":{"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","abstract":[],"title":"VigramSDK","type":"topic","role":"collection","images":[{"type":"icon","identifier":"logo.png"}],"url":"\/documentation\/vigramsdk","kind":"symbol"},"logo.png":{"variants":[{"url":"\/images\/com.vigram.VigramSDK\/logo.png","traits":["1x","light"]}],"alt":"Vigram logo.","identifier":"logo.png","type":"image"},"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AuthenticationError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AuthenticationError"}],"title":"AuthenticationError","abstract":[{"text":"AuthenticationError contains custom failure events when connecting to Authentication process.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError","url":"\/documentation\/vigramsdk\/authenticationerror"},"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError/failure(_:)":{"abstract":[{"type":"text","text":"Authentication is failure - Other error received from server"}],"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/failure(_:)","kind":"symbol","type":"topic","role":"symbol","title":"AuthenticationError.failure(_:)","url":"\/documentation\/vigramsdk\/authenticationerror\/failure(_:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failure","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}]}}}