{"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failure","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"modules":[{"name":"VigramSDK"}],"externalID":"s:9VigramSDK19AuthenticationErrorO7failureyACSScACmF","role":"symbol","symbolKind":"case","roleHeading":"Case","title":"AuthenticationError.failure(_:)"},"identifier":{"url":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/failure(_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Authentication is failure - Other error received from server","type":"text"}],"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failure"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/vigramsdk\/authenticationerror\/failure(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError"]]},"references":{"logo.png":{"identifier":"logo.png","variants":[{"url":"\/images\/com.vigram.VigramSDK\/logo.png","traits":["1x","light"]}],"alt":"Vigram logo.","type":"image"},"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError/failure(_:)":{"abstract":[{"type":"text","text":"Authentication is failure - Other error received from server"}],"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/failure(_:)","type":"topic","kind":"symbol","url":"\/documentation\/vigramsdk\/authenticationerror\/failure(_:)","title":"AuthenticationError.failure(_:)","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failure"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}]},"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError":{"type":"topic","navigatorTitle":[{"text":"AuthenticationError","kind":"identifier"}],"role":"symbol","title":"AuthenticationError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthenticationError","kind":"identifier"}],"url":"\/documentation\/vigramsdk\/authenticationerror","abstract":[{"text":"AuthenticationError contains custom failure events when connecting to Authentication process.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError"},"doc://com.vigram.VigramSDK/documentation/VigramSDK":{"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","url":"\/documentation\/vigramsdk","title":"VigramSDK","kind":"symbol","role":"collection","images":[{"type":"icon","identifier":"logo.png"}],"type":"topic","abstract":[]}}}