{"hierarchy":{"paths":[["doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"case","role":"symbol","title":"AuthenticationError.failure(_:)","externalID":"s:9VigramSDK19AuthenticationErrorO7failureyACSScACmF","modules":[{"name":"VigramSDK"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"failure"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"variants":[{"paths":["\/documentation\/vigramsdk\/authenticationerror\/failure(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failure"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"identifier":{"url":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/failure(_:)","interfaceLanguage":"swift"},"abstract":[{"text":"Authentication is failure - Other error received from server","type":"text"}],"references":{"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError/failure(_:)":{"role":"symbol","kind":"symbol","url":"\/documentation\/vigramsdk\/authenticationerror\/failure(_:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failure","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"title":"AuthenticationError.failure(_:)","type":"topic","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/failure(_:)","abstract":[{"text":"Authentication is failure - Other error received from server","type":"text"}]},"logo.png":{"type":"image","identifier":"logo.png","variants":[{"traits":["1x","light"],"url":"\/images\/com.vigram.VigramSDK\/logo.png"}],"alt":"Vigram logo."},"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError":{"navigatorTitle":[{"text":"AuthenticationError","kind":"identifier"}],"title":"AuthenticationError","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"AuthenticationError contains custom failure events when connecting to Authentication process."}],"type":"topic","url":"\/documentation\/vigramsdk\/authenticationerror","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AuthenticationError","kind":"identifier"}]},"doc://com.vigram.VigramSDK/documentation/VigramSDK":{"kind":"symbol","abstract":[],"images":[{"type":"icon","identifier":"logo.png"}],"type":"topic","title":"VigramSDK","url":"\/documentation\/vigramsdk","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","role":"collection"}}}